name: PHP Unit Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

jobs:
  unit-php:
    name: 'PHP ${{ matrix.php }} - WP ${{ matrix.wp }}'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        php: ['7.0', '5.6']
        wp: ['latest']
        coverage: [false]
        include:
          - php: '7.4'
            wp: 'latest'
            coverage: true

          - php: '5.6'
            wp: '5.3'

          - php: '7.4'
            wp: '5.6'

          - php: '7.4'
            wp: 'trunk'
            experimental: true

    # Disabled as long as WordPress trunk does not properly support PHP 8
    #          - php: '8.0'
    #            wp: 'trunk'
    #            coverage: false
    #            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Composer cache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
            ${{ runner.os }}-

      # PHP-Scoper only works on PHP 7.2+ and we need to prefix our dependencies to accurately test them.
      # So we temporarily switch PHP versions, do a full install and then remove the package.
      # Then switch back to the PHP version we want to test and delete the vendor directory.

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: cs2pr

      - name: Install prefixed dependencies
        run: npm run wp-env run composer 'install --prefer-dist --no-suggest --no-progress --no-interaction'

      - name: Configure WordPress version
        run: echo "{\"core\":\"WordPress/WordPress#${WP_VERSION:-master}\"}" >> .wp-env.override.json
        env:
          WP_VERSION: ${{ matrix.wp }}

      - name: Start Docker environment
        run: npm run wp-env start
        env:
          WP_ENV_PHP_VERSION: ${{ matrix.php }}

      - name: Enable Xdebug
        run: npm run wp-env start --update --xdebug
        if: ${{ matrix.coverage }}

      - name: Run tests
        run: |
          npm run test:php -- --coverage-clover build/logs/php-coverage.xml
          npm run test:php -- --coverage-clover build/logs/php-coverage-multisite.xml -c phpunit-multisite.xml.dist

      - name: Upload code coverage report
        uses: codecov/codecov-action@v1
        with:
          file: build/logs/*.xml
        if: ${{ matrix.coverage }}
