name: Migrate Templates
on:
  schedule:
    - cron: '0 12 * * 1'
jobs:
  update-template:
    name: Migrate Templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: |
          npm ci
          npx rollup --config assets/src/migration/rollup.config.migrate.js
        env:
          CI: true
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

      - name: Update templates and FTUE story
        run: npm run workflow:mirate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Migrate templates to latest version
          title: Migrate templates
          body: Update templates after running through migration
          branch: update/templates
          labels: Dependencies
